// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_GNt8WdKYoaxrOdC0xl0bm54cIZhpxjw',
    appId: '1:890322432461:web:d5fb08e0da55838e4f5484',
    messagingSenderId: '890322432461',
    projectId: 'boetepot-4bdcc',
    authDomain: 'boetepot-4bdcc.firebaseapp.com',
    storageBucket: 'boetepot-4bdcc.firebasestorage.app',
    measurementId: 'G-9QD51YCDR1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2ehxEKFE8Qzg0vq4f4XnKIvpWdOOBOu0',
    appId: '1:890322432461:android:27a511715dfadcd34f5484',
    messagingSenderId: '890322432461',
    projectId: 'boetepot-4bdcc',
    storageBucket: 'boetepot-4bdcc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCouH4Onbt3prKhS0pKr_7sojwqmmSRgI4',
    appId: '1:890322432461:ios:877963c17e9305544f5484',
    messagingSenderId: '890322432461',
    projectId: 'boetepot-4bdcc',
    storageBucket: 'boetepot-4bdcc.firebasestorage.app',
    iosBundleId: 'com.example.boetepot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCouH4Onbt3prKhS0pKr_7sojwqmmSRgI4',
    appId: '1:890322432461:ios:877963c17e9305544f5484',
    messagingSenderId: '890322432461',
    projectId: 'boetepot-4bdcc',
    storageBucket: 'boetepot-4bdcc.firebasestorage.app',
    iosBundleId: 'com.example.boetepot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_GNt8WdKYoaxrOdC0xl0bm54cIZhpxjw',
    appId: '1:890322432461:web:63acb066544b180c4f5484',
    messagingSenderId: '890322432461',
    projectId: 'boetepot-4bdcc',
    authDomain: 'boetepot-4bdcc.firebaseapp.com',
    storageBucket: 'boetepot-4bdcc.firebasestorage.app',
    measurementId: 'G-CNMHZWP5LP',
  );
}
