import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // generated by flutterfire configure
import 'package:firebase_auth/firebase_auth.dart';

import 'screens/sign_in_screen.dart';
import 'screens/home_shell.dart';
import 'services/user_service.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  runApp(const BoetePotApp());
}

class BoetePotApp extends StatelessWidget {
  const BoetePotApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'BoetePot',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: const Color(0xFFD4AF37)),
        useMaterial3: true,
      ),
      home: StreamBuilder<User?>(
        stream: FirebaseAuth.instance.authStateChanges(),
        builder: (context, snap) {
          final user = snap.data;
          if (snap.connectionState == ConnectionState.waiting) {
            return const Scaffold(body: Center(child: CircularProgressIndicator()));
          }
          if (user == null) {
            return const SignInScreen();
          } else {
            // Ensure we have a user doc
            UserService.ensureUserDoc(user);
            return const HomeShell();
          }
        },
      ),
    );
  }
}